import os
import re
import shutil
from collections import defaultdict, Counter
import json

class ExtendedErrorTaxonomyAnalyzer:
    """
    Analyzes compilation error taxonomy with detailed subcategories, file organization, and iteration support.
    
    This class is responsible for:
    1. Parsing .error files generated by compilers (GCC/Clang).
    2. Classifying errors into specific categories (e.g., Syntax, Type, Linker) using Regex patterns.
    3. Organizing the error files into a structured directory hierarchy based on the taxonomy.
    4. Calculating detailed statistics and proportions of errors across iterations and configurations.
    """
    
    def __init__(self, root_dir="input", output_dir="output"):
        """
        Initialize the analyzer.
        
        Args:
            root_dir (str): Path to the input directory containing validation iterations.
            output_dir (str): Path where the organized files and results will be saved.
        """
        self.root_dir = root_dir
        self.output_dir = output_dir
        
        # Dictionary of regex patterns to classify compilation errors.
        # Categories include: syntax, declaration, type, preprocessing, linker, architecture, etc.
        self.detailed_patterns = {
            'syntax': {
                'missing_syntax_elements': [r"expected ';' before", r"missing ';'", r"expected .* before", r"expected .* at end"],
                'malformed_expression': [r"expected expression before", r"expected primary-expression", r"syntax error before"],
                'invalid_statement': [r"expected statement", r"invalid use of", r"statement not within a loop", r"break statement not within", r"without a previous", r"computed goto must be pointer type", r"is a pointer; did you mean to use", r"exponent has no digits"],
                'parse_error': [r"parse error", r"syntax error at end of input"],
                'invalid_suffix': [r"invalid suffix"],
                'invalid_literal': [r"hexadecimal floating constants require an exponent", r"invalid or incomplete multibyte or wide character"]
            },
            'declaration': {
                'undeclared_variable': [r"undeclared \(first use", r"was not declared", r"error: .* undeclared"],
                'undeclared_function': [r"implicit declaration of function", r"undeclared.*function"],
                'multiple_definition': [r"redefinition of", r"multiple definition of", r"redeclared as different kind of symbol", r"duplicate label", r"redeclaration of", r"function definition declared"],
                'missing_prototype': [r"conflicting types for", r"previous declaration"],
                'invalid_declaration': [r"expected declaration", r"declaration does not declare", r"initializer element is not constant", r"label .* used but not defined", r"built-in function .* must be directly called"],
                'unknown_type': [r"unknown type name", r"error: unknown type name"]
            },
            'type': {
                'incompatible_assignment': [r"assignment from incompatible pointer type", r"incompatible types when assigning", r"assignment to expression with array type", r"assignment of read-only variable"],
                'incompatible_initialization': [r"initialization from incompatible pointer type", r"incompatible types when initializing"],
                'invalid_operands': [r"invalid operands to binary", r"invalid operands to binary", r"array subscript is not an integer"],
                'invalid_conversion': [r"cannot convert", r"invalid conversion", r"non-floating-point arguments in call to function", r"invalid initializer", r"onversion of scalar"],
                'pointer_mismatch': [r"dereferencing pointer to incomplete type", r"invalid type argument", r"in something not a structure or union", r"lvalue required as unary", r"lvalue required as left operand of assignment", r"has no member named", r"called object .* is not a function or function pointer", r"void value not ignored as it ought to be", r"lvalue required as increment operand", r"value used where a .* was expected", r"assignment of read-only location", r"cast from pointer to integer of different size", r"cast specifies array type", r"array type has incomplete element type", r"irst argument must be an integer or floating vector"],
                'type_mismatch': [r"incompatible type for argument", r"too few arguments to function", r"too many arguments to function", r"incompatible types when returning", r"non-floating-point argument in call to function", r"used vector type where scalar is required", r"cast to pointer from integer of different size", r"must be an integer constant", r"does not reduce to an integer constant", r"where an integer was expected", r"used where a .* where .* was expected", r"matching constraint references invalid operand number", r"conflicting type qualifiers"],
            },
            'preprocessing': {
                'missing_include': [r"fatal error: .*\.h: No such file", r".*\.h: No such file or directory"],
                'file_not_found': [r"No such file or directory", r"cannot open include file"],
                'macro_error': [r"macro .* redefined", r"unterminated #if", r"invalid preprocessing directive"],
                'include_error': [r"#include expects", r"error in #include", r"called object is not a function or function pointer"]
            },
            'linker': {
                'undefined_reference': [r"undefined reference to", r"unresolved external symbol"],
                'missing_library': [r"cannot find -l", r"library not found"],
                'linker_failure': [r"ld returned .* exit status", r"collect2: error: ld returned"],
                'symbol_error': [r"multiple definition of", r"first defined here"]
            },
            'architecture': {
                'isa_requirements': [r"needs isa option", r"__builtin_.* needs isa option"],
                'assembly_error': [r"operand size mismatch for", r"operand type mismatch for", r"inconsistent operand constraints", r"internal compiler error", r"invalid register name", r"operand has impossible constraints", r"cannot be used in .*asm", r"invalid .*asm", r"bad register name", r"register type mismatch for"],
                'target_mismatch': [r"target specific option mismatch", r"inlining failed.*always_inline.*option mismatch", r"subscripted value is neither array nor pointer nor vector"]
            },
            'other': {
                'unclassified': []
            }
        }
        # Pre-compile the regex patterns for better performance
        self.compiled_patterns = self._compile_detailed_patterns()
    
    def _compile_detailed_patterns(self):
        """
        Pre-compile detailed regex patterns for efficiency.
        
        Returns:
            dict: A nested dictionary with compiled regex objects.
        """
        compiled = {}
        for category, subcategories in self.detailed_patterns.items():
            compiled[category] = {}
            for subcat, patterns in subcategories.items():
                compiled[category][subcat] = [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
        return compiled
    
    def classify_error_detailed(self, error_content):
        """
        Classify error content into detailed taxonomy categories.
        
        This method scans the error content against all compiled regex patterns.
        It returns the first matching category and subcategory.
        
        Args:
            error_content (str): The content of the .error file.
            
        Returns:
            list: A list of tuples (category, subcategory). Currently returns the first match found.
        """
        classifications = []
        
        for category, subcategories in self.compiled_patterns.items():
            for subcat, patterns in subcategories.items():
                for pattern in patterns:
                    if pattern.search(error_content):
                        classifications.append((category, subcat))
                        break
                # If we found a match in this category, we stop scanning this category
                # to avoid duplicate matches for the same root cause.
                if classifications and classifications[-1][0] == category:
                    break
        
        # Return matched classifications or 'unclassified' if none found
        return classifications if classifications else [('other', 'unclassified')]
    
    def parse_error_file(self, filepath):
        """
        Parse a single .error file and return detailed error categories.
        
        Args:
            filepath (str): Absolute path to the error file.
            
        Returns:
            tuple: (file_content, classification_list)
        """
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            return content, self.classify_error_detailed(content)
        except Exception as e:
            print(f"Warning: Could not read {filepath}: {e}")
            return "", [('other', 'unclassified')]
    
    def create_output_structure(self):
        """
        Create the output directory structure.
        
        Removes the existing output directory if it exists to ensure a clean state,
        then creates a new one.
        """
        if os.path.exists(self.output_dir):
            shutil.rmtree(self.output_dir)
        os.makedirs(self.output_dir)
    
    def copy_error_file(self, source_path, iteration, model, ir_type, opt_level, filename, category, subcategory):
        """
        Copy error file to organized output structure.
        
        The structure will be:
        output_dir / iteration / category / subcategory / model / ir_type / opt_level / filename
        
        Args:
            source_path (str): Original file path.
            iteration (str): Iteration ID (e.g., 'iter_1').
            model (str): Model name.
            ir_type (str): IR type (e.g., 'O0', 'O2').
            opt_level (str): Optimization level.
            filename (str): Name of the file.
            category (str): Error category (e.g., 'syntax').
            subcategory (str): Error subcategory (e.g., 'missing_semicolon').
        """
        target_dir = os.path.join(self.output_dir, iteration, category, subcategory, model, ir_type, opt_level)
        os.makedirs(target_dir, exist_ok=True)
        
        target_path = os.path.join(target_dir, filename)
        shutil.copy2(source_path, target_path)
    
    def analyze_and_organize(self):
        """
        Analyze directory structure with iterations and organize files by error taxonomy.
        
        This is the main driver method that traverses the directory tree, parses files,
        classifies them, and copies them to the new structure while aggregating stats.
        
        Returns:
            tuple: (results, file_counts, iteration_file_counts) containing nested dictionaries with statistics.
        """
        # Six-level defaultdict: iteration -> model -> ir_type -> opt_level -> category -> subcategory
        results = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(int))))))
        file_counts = defaultdict(lambda: defaultdict(int))  # Overall counts across all iterations
        iteration_file_counts = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))  # Counts per iteration
        
        if not os.path.exists(self.root_dir):
            print(f"Error: Directory {self.root_dir} does not exist")
            return results, file_counts, iteration_file_counts
        
        self.create_output_structure()
        
        total_files = 0
        processed_files = 0
        
        # Traverse the directory structure:
        # root_dir -> iteration -> model -> ir_type -> opt_level -> error_files
        for iteration in os.listdir(self.root_dir):
            iteration_path = os.path.join(self.root_dir, iteration)
            if not os.path.isdir(iteration_path):
                continue
            
            for model in os.listdir(iteration_path):
                model_path = os.path.join(iteration_path, model)
                if not os.path.isdir(model_path):
                    continue
                
                for ir_type in os.listdir(model_path):
                    ir_path = os.path.join(model_path, ir_type)
                    if not os.path.isdir(ir_path):
                        continue
                    
                    for opt_level in os.listdir(ir_path):
                        opt_path = os.path.join(ir_path, opt_level)
                        if not os.path.isdir(opt_path):
                            continue
                        
                        # Find all .error files in this leaf directory
                        error_files = [f for f in os.listdir(opt_path) if f.endswith('.error')]
                        total_files += len(error_files)
                        
                        for error_file in error_files:
                            error_path = os.path.join(opt_path, error_file)
                            content, classifications = self.parse_error_file(error_path)
                            
                            for category, subcategory in classifications:
                                # Update statistics
                                results[iteration][model][ir_type][opt_level][category][subcategory] += 1
                                file_counts[category][subcategory] += 1
                                iteration_file_counts[iteration][category][subcategory] += 1
                                
                                # Copy file to the organized directory structure
                                self.copy_error_file(error_path, iteration, model, ir_type, opt_level, 
                                                   error_file, category, subcategory)
                            
                            processed_files += 1
        
        print(f"Processed {processed_files} error files out of {total_files} total files across {len(results)} iterations")
        return results, file_counts, iteration_file_counts
    
    def calculate_detailed_proportions(self, results):
        """
        Calculate relative proportions for detailed taxonomy with iteration support.
        
        Computes percentages for each error category and subcategory relative to the total errors
        within that specific configuration context.
        
        Args:
            results (dict): The raw count data returned by analyze_and_organize.
            
        Returns:
            dict: A complex dictionary structure containing counts and calculated proportions.
        """
        proportions = {}
        
        for iteration in results:
            proportions[iteration] = {}
            for model in results[iteration]:
                proportions[iteration][model] = {}
                for ir_type in results[iteration][model]:
                    proportions[iteration][model][ir_type] = {}
                    for opt_level in results[iteration][model][ir_type]:
                        config_data = results[iteration][model][ir_type][opt_level]
                        
                        # Calculate totals for this configuration
                        category_totals = {}
                        grand_total = 0
                        
                        for category, subcategories in config_data.items():
                            category_total = sum(subcategories.values())
                            category_totals[category] = category_total
                            grand_total += category_total
                        
                        if grand_total > 0:
                            config_props = {
                                'category_counts': category_totals,
                                'category_proportions': {cat: count/grand_total for cat, count in category_totals.items()},
                                'subcategory_details': {},
                                'total_errors': grand_total
                            }
                            
                            # Calculate subcategory proportions
                            for category, subcategories in config_data.items():
                                if category_totals[category] > 0:
                                    config_props['subcategory_details'][category] = {
                                        'counts': dict(subcategories),
                                        'proportions': {subcat: count/category_totals[category] 
                                                      for subcat, count in subcategories.items()}
                                    }
                            
                            proportions[iteration][model][ir_type][opt_level] = config_props
        
        return proportions
    
    def calculate_iteration_comparison(self, iteration_file_counts):
        """
        Calculate comparison statistics between different iterations.
        
        This enables tracking how error rates and distributions change over time (e.g., as the model improves).
        
        Args:
            iteration_file_counts (dict): Counts per iteration.
            
        Returns:
            dict: Statistics comparing iterations.
        """
        iteration_comparison = {}
        all_iterations = list(iteration_file_counts.keys())
        
        for iteration in all_iterations:
            iteration_total = sum(sum(subcats.values()) for subcats in iteration_file_counts[iteration].values())
            
            iteration_stats = {
                'total_errors': iteration_total,
                'category_distribution': {},
                'subcategory_distribution': {}
            }
            
            # Category-level comparison
            for category in iteration_file_counts[iteration]:
                category_total = sum(iteration_file_counts[iteration][category].values())
                iteration_stats['category_distribution'][category] = {
                    'count': category_total,
                    'proportion': category_total / iteration_total if iteration_total > 0 else 0
                }
                
                # Subcategory-level details
                iteration_stats['subcategory_distribution'][category] = {}
                for subcategory, count in iteration_file_counts[iteration][category].items():
                    iteration_stats['subcategory_distribution'][category][subcategory] = {
                        'count': count,
                        'proportion_of_category': count / category_total if category_total > 0 else 0,
                        'proportion_of_total': count / iteration_total if iteration_total > 0 else 0
                    }
            
            iteration_comparison[iteration] = iteration_stats
        
        return iteration_comparison
    
    def print_detailed_summary(self, proportions, file_counts, iteration_file_counts):
        """
        Print a comprehensive summary of detailed error taxonomy analysis to the console.
        """
        print("=== DETAILED COMPILATION ERROR TAXONOMY ANALYSIS WITH ITERATIONS ===\n")
        
        # Overall statistics across all iterations
        print("OVERALL ERROR DISTRIBUTION (ALL ITERATIONS):")
        total_errors = sum(sum(subcats.values()) for subcats in file_counts.values())
        
        for category in sorted(file_counts.keys()):
            category_total = sum(file_counts[category].values())
            print(f"\n{category.upper()}: {category_total} ({category_total/total_errors:.2%})")
            
            for subcat in sorted(file_counts[category].keys()):
                count = file_counts[category][subcat]
                subcat_prop = count / category_total if category_total > 0 else 0
                print(f"  {subcat}: {count} ({subcat_prop:.2%})")
        
        print(f"\nTotal errors analyzed: {total_errors} across {len(iteration_file_counts)} iterations")
        
        # Per-iteration summary
        print("\n" + "="*60)
        print("PER-ITERATION SUMMARY:")
        
        for iteration in sorted(iteration_file_counts.keys()):
            iteration_total = sum(sum(subcats.values()) for subcats in iteration_file_counts[iteration].values())
            print(f"\nIteration {iteration}: {iteration_total} errors")
            
            for category in sorted(iteration_file_counts[iteration].keys()):
                category_total = sum(iteration_file_counts[iteration][category].values())
                print(f"  {category}: {category_total} ({category_total/iteration_total:.2%})")
        
        print("\n" + "="*60 + "\n")
        
        # Sample detailed breakdown (first iteration only for brevity)
        first_iteration = sorted(proportions.keys())[0] if proportions else None
        if first_iteration:
            print(f"SAMPLE DETAILED BREAKDOWN (Iteration {first_iteration}):\n")
            
            for model in sorted(proportions[first_iteration].keys())[:2]:  # Limit to 2 models for brevity
                print(f"Model: {model}")
                for ir_type in sorted(proportions[first_iteration][model].keys())[:2]:
                    print(f"  IR: {ir_type}")
                    for opt_level in sorted(proportions[first_iteration][model][ir_type].keys())[:2]:
                        config = proportions[first_iteration][model][ir_type][opt_level]
                        print(f"    Optimization: {opt_level} ({config['total_errors']} errors)")
                        
                        for category in sorted(config['category_counts'].keys())[:3]:
                            cat_count = config['category_counts'][category]
                            cat_prop = config['category_proportions'][category]
                            print(f"      {category}: {cat_count} ({cat_prop:.2%})")
                print()
    
    def export_detailed_results(self, proportions, file_counts, iteration_file_counts,
                               overall_file="detailed_error_taxonomy_overall.json",
                               iterations_file="detailed_error_taxonomy_by_iteration.json",
                               comparison_file="iteration_comparison.json",
                               summary_file="error_summary_with_iterations.json"):
        """
        Export detailed results to JSON files for external use/visualization.
        
        Args:
            proportions (dict): Detailed proportions data.
            file_counts (dict): Overall raw counts.
            iteration_file_counts (dict): Per-iteration raw counts.
            overall_file (str): Output filename for overall data.
            iterations_file (str): Output filename for per-iteration data.
            comparison_file (str): Output filename for comparison data.
            summary_file (str): Output filename for summary statistics.
        """
        
        # Export overall detailed proportions (all iterations combined)
        with open(overall_file, 'w') as f:
            json.dump(proportions, f, indent=2)
        
        # Export iteration-specific analysis
        iteration_analysis = {
            'by_iteration': proportions,
            'iteration_file_counts': dict(iteration_file_counts)
        }
        with open(iterations_file, 'w') as f:
            json.dump(iteration_analysis, f, indent=2)
        
        # Export iteration comparison
        iteration_comparison = self.calculate_iteration_comparison(iteration_file_counts)
        with open(comparison_file, 'w') as f:
            json.dump(iteration_comparison, f, indent=2)
        
        # Export enhanced summary statistics
        summary = {
            'overall_distribution': dict(file_counts),
            'iteration_distribution': dict(iteration_file_counts),
            'total_errors': sum(sum(subcats.values()) for subcats in file_counts.values()),
            'total_iterations': len(iteration_file_counts),
            'categories': list(file_counts.keys()),
            'output_structure_created': True,
            'output_directory': self.output_dir,
            'iteration_comparison_summary': iteration_comparison
        }
        
        with open(summary_file, 'w') as f:
            json.dump(summary, f, indent=2)
        
        print(f"Overall results exported to {overall_file}")
        print(f"Iteration-specific analysis exported to {iterations_file}")
        print(f"Iteration comparison exported to {comparison_file}")
        print(f"Enhanced summary statistics exported to {summary_file}")
        print(f"Organized error files copied to {self.output_dir}/")

def main():
    """Main execution entry point."""
    analyzer = ExtendedErrorTaxonomyAnalyzer()
    
    print("Analyzing detailed error taxonomy with iterations and organizing files...")
    results, file_counts, iteration_file_counts = analyzer.analyze_and_organize()
    
    if not results:
        print("No error files found or unable to access directory structure.")
        return
    
    proportions = analyzer.calculate_detailed_proportions(results)
    analyzer.print_detailed_summary(proportions, file_counts, iteration_file_counts)
    analyzer.export_detailed_results(proportions, file_counts, iteration_file_counts)
    
    print(f"\nAnalysis complete! Check the '{analyzer.output_dir}' directory for organized error files.")

if __name__ == "__main__":
    main()